language: python

python:
  - 2.7
  - 3.4

install:
  - python setup.py sdist 
  - pip install dist/*.tar.gz

script:
  - cd crowfood/test
  - nosetests
  - cd ../..
  
deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: ""
  on:
    tags: true
    all_branches: true