language: python

python:
  - 2.7
  - 3.4

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install coverage

script:
  - cd crowfood/test
  - echo $PYTHONPATH
  - python -c "from __future__ import print_function; import crowfood; print(crowfood.__file__)"
  - nosetests --with-coverage --cover-package=crowfood
  
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then
      pip install coveralls ;
      coveralls ;
    fi
  - cd ../..
  
deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: "QL/YehkdkoeKudEkE6OHUTFtYF5mhXN93fMxcEY/LwCLv4IA3a1qpYCcq1RLcSX3qjMG29TuADPNghLrc6Vqb3UfxodKJSF0MhKzbVEYxN3ylKLjGklVkyztb6pRApv32DWnvobTTSgS8Dz7vtZam6wq10cLLBk8r9WL9Cxzd7A="
  on:
    tags: true
    all_branches: true
    python: 3.4