language: python

python:
  - 2.7
  - 3.4

install:
  - python setup.py sdist 
  - pip install dist/*.tar.gz

script:
  - cd crowfood/test
  - nosetests  --with-coverage --cover-package=crowfood
  - cd ../..
  
after_success:
  - pip install coveralls
  - coveralls
  
deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: "QL/YehkdkoeKudEkE6OHUTFtYF5mhXN93fMxcEY/LwCLv4IA3a1qpYCcq1RLcSX3qjMG29TuADPNghLrc6Vqb3UfxodKJSF0MhKzbVEYxN3ylKLjGklVkyztb6pRApv32DWnvobTTSgS8Dz7vtZam6wq10cLLBk8r9WL9Cxzd7A="
  on:
    tags: true
    all_branches: true
    python: 3.4